### ISSUE TITLE
Unable to load custom image

### ISSUE THREAD

**Issue by Dragonfire967** [DSH105/HoloAPI#93]
Hey, I am trying to load a custom image for HoloAPI on my server, and keep getting the following error:

"[HoloAPI] ... Failed to load custom image. Make sure that it is correctly configured in config.yml."

My config.yml has this added to it (by me), otherwise is the same as default:

```
images:
    cgames:
      path: cgames.png
      characterType: BLOCK
      height: 20
      type: FILE
      requiresBorder: false
```

And there are no errors at all in the server logs / console.

Any help would be appreciated, as I wanted to have my server group logo displayed at spawn.  Also, yes, the file I am setting the path to does exist, and there are no typos.
